### ISSUE TITLE
geopandas: ImportError: libpoppler.so.76: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jmp75** [csiro-hydrogeology/pyela#17]
Trying to fix the travis build failure

`import geopandas as gpd`

after running unit tests in a new environment created with:
```yaml
name: ela_test
channels:
  - conda
  - conda-forge
dependencies: 
  - rasterio=1.0.21
  - cartopy=0.17.0
  - geopandas=0.4.1
  - pandas=0.24.2
  - nltk=3.4.4
  - scikit-learn=0.21.2
  - matplotlib=3.1.0
  - vtk=8.2.0
  - pytest-cov=2.7.1
  - cython=0.29.12
  - coverage=4.5.3
  - wordcloud=1.5.0
  - pyqt=5.9.2
  - mayavi=4.7.1
  - codecov=2.0.15
  - pip
  - pip:
    #  - mayavi==4.7.1 # no need now that suitable conda pkg
    - git+https://github.com/jmp75/striplog@master#egg=striplog

```
